# .readthedocs.yaml for devguide-pt-br

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - rm -rf ../devguide/
    - git clone https://github.com/python/devguide ../devguide
    - mkdir -p ../devguide/locales/pt_BR/
    - ln -s ./ ../devguide/locales/pt_BR/LC_MESSAGES/
    - make -C ../devguide/ dirhtml BUILDDIR=_readthedocs SPHINXOPTS="-Dlanguage=pt_BR -Dgettext_compact=0"
    - mkdir _readthedocs
    - mv ../devguide/_readthedocs/dirhtml _readthedocs/html
