# .readthedocs.yaml for devguide-pt-br

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - git clone https://github.com/python/devguide
      - mkdir -p devguide/locales/pt_BR/LC_MESSAGES/
      - cp -R *.po *.*po devguide/locales/pt_BR/LC_MESSAGES/

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: devguide/conf.py

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: devguide/requirements.txt
