# .readthedocs.yaml for devguide-pt-br

# Required
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - rm -rf ../devguide/
    - git clone https://github.com/python/devguide ../devguide
    - mkdir -p ../devguide/locales/pt_BR/LC_MESSAGES/
    - cp -R ./ ../devguide/locales/pt_BR/LC_MESSAGES/
    - pip install -U pip
    - pip install -U -r ../devguide/requirements.txt
    - sphinx-build -c ../devguide/ -Dlanguage=pt_BR -Dgettext_compact=0 ../devguide/ _readthedocs/html
