name: Translation stats

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache-pip: true
      - name: Install dependencies
        run: |
          python -m pip install potodo
      - name: Regenerate stats.rst
        run: |
          python stats.py -f stats.rst
      - name: Show stats.rst
        run: |
          cat stats.rst
      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Update translation stats" --allow-empty stats.rst
          git push

